import type { LuauIR, TypeDecl } from "./type-extractor";

export function emitIR(ir: LuauIR, depth = 0): string {
    switch (ir.kind) {
        case "primitive":
            return ir.name;
        case "void":
            return "()";
        case "never":
            return "never";
        case "any":
            return "any";

        case "optional": {
            const inner = emitIR(ir.inner, depth);
            // don't double-wrap
            return inner.endsWith("?") ? inner : `${inner}?`;
        }

        case "array":
            return `{${emitIR(ir.element, depth)}}`;

        case "map":
            return `{[${emitIR(ir.key, depth)}]: ${emitIR(ir.value, depth)}}`;

        case "set":
            return `{[${emitIR(ir.key, depth)}]: boolean}`;

        case "tuple":
            return `(${ir.elements.map((e) => emitIR(e, depth)).join(", ")})`;

        case "union":
            return ir.types.map((t) => emitIR(t, depth)).join(" | ");

        case "intersection":
            return ir.types.map((t) => emitIR(t, depth)).join(" & ");

        case "reference": {
            if (ir.typeArgs && ir.typeArgs.length > 0) {
                const args = ir.typeArgs.map((a) => emitIR(a, depth)).join(", ");
                return `${ir.name}<${args}>`;
            }
            return ir.name;
        }

        case "function": {
            const params = ir.params
                .map((p) => {
                    const type = emitIR(p.type, depth);
                    return p.name === "_" ? type : `${p.name}: ${type}`;
                })
                .join(", ");
            const ret = emitIR(ir.returns, depth);
            return `(${params}) -> ${ret}`;
        }

        case "conditional": {
            // should be split upstream; fallback to intersection
            return `(${emitIR(ir.trueBranch, depth)}) & (${emitIR(ir.falseBranch, depth)})`;
        }

        case "object": {
            if (ir.fields.length === 0 && !ir.indexSig) return "{}";
            const indent = "    ".repeat(depth + 1);
            const close = "    ".repeat(depth);
            const parts: string[] = [];

            if (ir.indexSig) {
                parts.push(
                    `${indent}[${emitIR(ir.indexSig.key, depth + 1)}]: ${emitIR(ir.indexSig.value, depth + 1)}`,
                );
            }
            for (const f of ir.fields) {
                const t = emitIR(f.type, depth + 1);
                const luauType = f.optional ? (t.endsWith("?") ? t : `${t}?`) : t;
                parts.push(`${indent}${f.name}: ${luauType}`);
            }
            return `{\n${parts.join(",\n")},\n${close}}`;
        }
    }
}

export function emitDecl(decl: TypeDecl): string {
    const params = decl.typeParams.length > 0 ? `<${decl.typeParams.join(", ")}>` : "";
    return `export type ${decl.name}${params} = ${emitIR(decl.body)}`;
}

export function emitTypesFile(decls: Map<string, TypeDecl>, usedNames: Set<string>): string {
    const lines = ["-- [generated by rbxts-transformer-luau-annotate — do not edit]", ""];

    // collect all declarations including transitive dependencies
    const toEmit = new Set<string>();

    function collect(name: string) {
        if (toEmit.has(name)) return;
        if (!decls.has(name)) return;
        toEmit.add(name);
        // collect dependencies from the body
        collectDeps(decls.get(name)!.body);
    }

    function collectDeps(ir: LuauIR) {
        switch (ir.kind) {
            case "reference":
                collect(ir.name);
                ir.typeArgs?.forEach(collectDeps);
                break;
            case "optional":
                collectDeps(ir.inner);
                break;
            case "array":
                collectDeps(ir.element);
                break;
            case "map":
                collectDeps(ir.key);
                collectDeps(ir.value);
                break;
            case "set":
                collectDeps(ir.key);
                break;
            case "union":
            case "intersection":
                ir.types.forEach(collectDeps);
                break;
            case "tuple":
                ir.elements.forEach(collectDeps);
                break;
            case "function":
                ir.params.forEach((p) => collectDeps(p.type));
                collectDeps(ir.returns);
                break;
            case "object":
                ir.fields.forEach((f) => collectDeps(f.type));
                if (ir.indexSig) {
                    collectDeps(ir.indexSig.key);
                    collectDeps(ir.indexSig.value);
                }
                break;
            case "conditional":
                collectDeps(ir.trueBranch);
                collectDeps(ir.falseBranch);
                break;
        }
    }

    for (const name of usedNames) collect(name);

    // emit in insertion order (Map preserves order)
    for (const [name, decl] of decls) {
        if (toEmit.has(name)) {
            lines.push(emitDecl(decl));
            lines.push("");
        }
    }

    lines.push("return {}");
    return lines.join("\n");
}
